export const CRM_TEMPLATES: Record<string, { name: string; icon: string; fieldMap: Record<string, string>; notes: string }> = {
	hubspot: {
		name: 'HubSpot',
		icon: '🟠',
		notes: 'Export from HubSpot: Contacts → Export → All properties',
		fieldMap: {
			'First Name': 'first_name',
			'Last Name': 'last_name',
			'Email Address': 'email',
			'Phone Number': 'phone',
			'Mobile Phone Number': 'phone',
			'Company Name': 'company',
			'Job Title': 'title',
			'Website URL': 'website',
			'LinkedIn Bio': 'linkedin_url',
			'Lifecycle Stage': 'contact_type',
			'Lead Source': 'lead_source',
			'Notes': 'notes',
		},
	},
	salesforce: {
		name: 'Salesforce',
		icon: '☁️',
		notes: 'Export from Salesforce: Reports → Contacts → Export Details → CSV',
		fieldMap: {
			'Full Name': 'name',
			'First Name': 'first_name',
			'Last Name': 'last_name',
			'Email': 'email',
			'Phone': 'phone',
			'Mobile': 'phone',
			'Account Name': 'company',
			'Title': 'title',
			'Website': 'website',
			'Lead Source': 'lead_source',
			'Description': 'notes',
		},
	},
	pipedrive: {
		name: 'Pipedrive',
		icon: '🟢',
		notes: 'Export from Pipedrive: Contacts → … → Export to CSV',
		fieldMap: {
			'Person name': 'name',
			'Email': 'email',
			'Phone': 'phone',
			'Organization': 'company',
			'Job title': 'title',
			'Notes': 'notes',
			'Label': 'contact_type',
		},
	},
	google: {
		name: 'Google Contacts',
		icon: '🔵',
		notes: 'Export from Google Contacts: … → Export → Google CSV',
		fieldMap: {
			'Name': 'name',
			'Given Name': 'first_name',
			'Family Name': 'last_name',
			'E-mail 1 - Value': 'email',
			'Phone 1 - Value': 'phone',
			'Organization 1 - Name': 'company',
			'Organization 1 - Title': 'title',
			'Website 1 - Value': 'website',
			'Notes': 'notes',
		},
	},
	zoho: {
		name: 'Zoho CRM',
		icon: '🔴',
		notes: 'Export from Zoho: Contacts → Import/Export → Export Contacts',
		fieldMap: {
			'Full Name': 'name',
			'First Name': 'first_name',
			'Last Name': 'last_name',
			'Email': 'email',
			'Phone': 'phone',
			'Mobile': 'phone',
			'Account Name': 'company',
			'Title': 'title',
			'Website': 'website',
			'Lead Source': 'lead_source',
			'Description': 'notes',
		},
	},
	close: {
		name: 'Close CRM',
		icon: '⚫',
		notes: 'Export from Close: Contacts → Export',
		fieldMap: {
			'Contact Name': 'name',
			'Email': 'email',
			'Phone': 'phone',
			'Lead Company': 'company',
			'Title': 'title',
			'Lead URL': 'website',
			'Note': 'notes',
		},
	},
	linkedin: {
		name: 'LinkedIn',
		icon: '🔷',
		notes: 'Export from LinkedIn: Settings → Data Privacy → Get a copy of your data → Connections',
		fieldMap: {
			'First Name': 'first_name',
			'Last Name': 'last_name',
			'Email Address': 'email',
			'Company': 'company',
			'Position': 'title',
			'Connected On': 'skip',
		},
	},
};
