import { json, error } from '@sveltejs/kit';
import { requireAuth, supabaseAdmin } from '$lib/server/supabase';
import { env } from '$env/dynamic/private';
import type { RequestHandler } from './$types';

export const GET: RequestHandler = async ({ request }) => {
	const user = await requireAuth(request);
	const { data } = await supabaseAdmin
		.from('generated_reports')
		.select('*, client:clients(name), project:projects(name)')
		.eq('user_id', user.id)
		.order('created_at', { ascending: false })
		.limit(50);
	return json(data ?? []);
};

export const POST: RequestHandler = async ({ request }) => {
	const user = await requireAuth(request);
	const body = await request.json();
	const { type, clientId, projectId, campaignId, dateFrom, dateTo, title, extraContext } = body;

	if (!type || !title) throw error(400, 'type and title required');

	let content = '';
	let htmlContent = '';

	if (type === 'action_report') {
		// Gather call data for the period
		let callQuery = supabaseAdmin
			.from('calls')
			.select('outcome, call_duration_seconds, summary, notes, created_at, contact:contacts(name, company)')
			.eq('user_id', user.id);

		if (dateFrom) callQuery = callQuery.gte('created_at', dateFrom);
		if (dateTo)   callQuery = callQuery.lte('created_at', dateTo + 'T23:59:59');

		const { data: calls } = await callQuery.order('created_at', { ascending: false }).limit(100);
		const callList = calls ?? [];

		const outcomes: Record<string, number> = {};
		for (const c of callList) {
			const o = c.outcome ?? 'no_outcome';
			outcomes[o] = (outcomes[o] ?? 0) + 1;
		}

		const summaries = callList
			.filter(c => c.summary)
			.slice(0, 10)
			.map(c => `- ${(c.contact as {name:string})?.name ?? 'Contact'}: ${c.summary}`)
			.join('\n');

		const totalMins = Math.round(callList.reduce((s, c) => s + (c.call_duration_seconds ?? 0), 0) / 60);

		const prompt = `Generate a professional sales development action report for a client.

Period: ${dateFrom ?? 'All time'} to ${dateTo ?? 'Present'}
Total Calls: ${callList.length}
Total Talk Time: ${totalMins} minutes

Call Outcomes:
${Object.entries(outcomes).map(([k,v]) => `- ${k.replace(/_/g,' ')}: ${v}`).join('\n')}

${summaries ? `Recent Call Highlights:\n${summaries}` : ''}

${extraContext ? `Additional Context:\n${extraContext}` : ''}

Generate a professional markdown report with:
1. Executive Summary (2-3 sentences)
2. Activity Highlights (bullet points)  
3. Key Insights (what we learned)
4. Recommendations (next steps)
5. Performance Metrics table

Format as clean, professional markdown. Be specific and actionable.`;

		const claudeRes = await fetch('https://api.anthropic.com/v1/messages', {
			method: 'POST',
			headers: {
				'x-api-key': env.ANTHROPIC_API_KEY,
				'anthropic-version': '2023-06-01',
				'content-type': 'application/json',
			},
			body: JSON.stringify({
				model: 'claude-sonnet-4-6',
				max_tokens: 1500,
				messages: [{ role: 'user', content: prompt }],
			}),
		});

		if (claudeRes.ok) {
			const claudeData = await claudeRes.json() as { content: Array<{type:string;text:string}> };
			content = claudeData.content[0]?.text ?? '';
		} else {
			content = `# ${title}\n\nFailed to generate report. Check ANTHROPIC_API_KEY.`;
		}

		htmlContent = markdownToHtml(content, title);
	}

	const { data: report, error: e } = await supabaseAdmin
		.from('generated_reports')
		.insert({
			user_id: user.id,
			client_id: clientId ?? null,
			project_id: projectId ?? null,
			campaign_id: campaignId ?? null,
			report_type: type,
			report_title: title,
			date_from: dateFrom ?? null,
			date_to: dateTo ?? null,
			content,
			html_content: htmlContent,
		})
		.select()
		.single();

	if (e) throw error(500, e.message);
	return json(report);
};

// Minimal markdown → HTML
function markdownToHtml(md: string, title: string): string {
	let html = md
		.replace(/^### (.+)$/gm, '<h3>$1</h3>')
		.replace(/^## (.+)$/gm, '<h2>$1</h2>')
		.replace(/^# (.+)$/gm, '<h1>$1</h1>')
		.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
		.replace(/\*(.+?)\*/g, '<em>$1</em>')
		.replace(/^- (.+)$/gm, '<li>$1</li>')
		.replace(/\n\n/g, '</p><p>')
		.replace(/(<li>.*<\/li>)/gs, '<ul>$1</ul>');

	return `<div style="font-family:Georgia,serif;max-width:700px;margin:0 auto;padding:40px;color:#111">
<h1 style="border-bottom:2px solid #111;padding-bottom:12px">${title}</h1>
<div>${html}</div>
<p style="margin-top:40px;font-size:12px;color:#666">Generated by Edelhaus on ${new Date().toLocaleDateString()}</p>
</div>`;
}
