<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { BRAND, titleFor } from '$lib/brand';

	let report = $state<{report_title:string;html_content:string;created_at:string;report_type:string}|null>(null);
	let safeHtml = $state('');
	let loading = $state(true);
	let notFound = $state(false);

	onMount(async () => {
		const token = $page.params.token;
		const res = await fetch(`/api/portal/view/${token}`);
		if (res.ok) {
			report = await res.json();
			// Sanitize the stored report HTML before rendering it on this public page.
			// Dynamic import keeps DOMPurify out of any SSR pass (it needs the DOM).
			if (report?.html_content) {
				const { default: DOMPurify } = await import('dompurify');
				safeHtml = DOMPurify.sanitize(report.html_content);
			}
		} else {
			notFound = true;
		}
		loading = false;
	});
</script>

<svelte:head>
	<title>{titleFor(report?.report_title ?? 'Report')}</title>
	<meta name="robots" content="noindex" />
</svelte:head>

{#if loading}
	<div class="min-h-screen bg-[#0a0a0a] flex items-center justify-center">
		<p class="text-[#6e6e6e] text-sm">Loading report...</p>
	</div>
{:else if notFound}
	<div class="min-h-screen bg-[#0a0a0a] flex items-center justify-center">
		<div class="text-center">
			<p class="text-white text-lg font-semibold mb-2">Report not found</p>
			<p class="text-[#6e6e6e] text-sm">This link may have expired or been revoked.</p>
		</div>
	</div>
{:else if report}
	<div class="min-h-screen bg-white">
		{#if safeHtml}
			<!-- eslint-disable-next-line svelte/no-at-html-tags -- sanitized via DOMPurify above -->
			{@html safeHtml}
		{:else}
			<div class="max-w-2xl mx-auto p-8">
				<h1 class="text-2xl font-semibold text-gray-900 mb-4">{report.report_title}</h1>
				<p class="text-gray-500 text-sm">No content available.</p>
			</div>
		{/if}
		<div class="border-t border-gray-100 p-4 text-center bg-gray-50">
			<p class="text-xs text-gray-400">Generated by {BRAND} · Shared {new Date(report.created_at).toLocaleDateString()}</p>
		</div>
	</div>
{/if}
