<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';

	let report = $state<{report_title:string;html_content:string;created_at:string;report_type:string}|null>(null);
	let loading = $state(true);
	let notFound = $state(false);

	onMount(async () => {
		const token = $page.params.token;
		const res = await fetch(`/api/portal/view/${token}`);
		if (res.ok) report = await res.json();
		else notFound = true;
		loading = false;
	});
</script>

<svelte:head>
	<title>{report?.report_title ?? 'Report'} — LeadOS</title>
	<meta name="robots" content="noindex" />
</svelte:head>

{#if loading}
	<div class="min-h-screen bg-[#0a0a0a] flex items-center justify-center">
		<p class="text-[#444] text-sm">Loading report...</p>
	</div>
{:else if notFound}
	<div class="min-h-screen bg-[#0a0a0a] flex items-center justify-center">
		<div class="text-center">
			<p class="text-white text-lg font-semibold mb-2">Report not found</p>
			<p class="text-[#444] text-sm">This link may have expired or been revoked.</p>
		</div>
	</div>
{:else if report}
	<div class="min-h-screen bg-white">
		{#if report.html_content}
			{@html report.html_content}
		{:else}
			<div class="max-w-2xl mx-auto p-8">
				<h1 class="text-2xl font-semibold text-gray-900 mb-4">{report.report_title}</h1>
				<p class="text-gray-500 text-sm">No content available.</p>
			</div>
		{/if}
		<div class="border-t border-gray-100 p-4 text-center bg-gray-50">
			<p class="text-xs text-gray-400">Generated by LeadOS · Shared {new Date(report.created_at).toLocaleDateString()}</p>
		</div>
	</div>
{/if}
